### Тут очень вкратце поговорим про numpy

NumPy — это библиотека Python для работы с массивами и матрицами, а также для выполнения разнообразных математических и логических операций над ними. Эта библиотека предоставляет высокопроизводительные структуры данных и реализует широкий набор функций для обработки числовых данных.

Основные особенности NumPy:

1. Массивы и матрицы: Основная структура данных NumPy — это массивы (numpy.ndarray), которые могут быть многомерными.
2. Высокая производительность: NumPy написана на C, что делает операции с массивами намного быстрее, чем стандартные операции Python.
3. Широкий набор функций: Включает функции для линейной алгебры, статистики, генерации случайных чисел и других математических операций.
4. Интеграция с другими библиотеками: NumPy хорошо интегрируется с такими библиотеками, как SciPy, Pandas, Matplotlib и другими.

**Примеры использования:**
1. Создание массивов

In [1]:
import numpy as np

# Одномерный массив
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Двумерный массив (матрица)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


2. Операции с массивами

In [2]:
# Сложение массивов
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)  # [5, 7, 9]

# Умножение массива на скаляр
scalar_mult = arr1 * 3
print(scalar_mult)  # [3, 6, 9]


[5 7 9]
[3 6 9]


3. Функции NumPy

In [3]:
# Создание массива из 10 чисел, равномерно распределённых между 0 и 1
linspace_array = np.linspace(0, 1, 10)
print(linspace_array)

# Среднее значение массива
mean_value = np.mean(arr)
print(mean_value)  # 3.0

# Стандартное отклонение массива
std_dev = np.std(arr)
print(std_dev)  # 1.4142135623730951


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
3.0
1.4142135623730951


4. Генерация случайных чисел

In [4]:
# Случайные числа от 0 до 1
random_array = np.random.rand(5)
print(random_array)

# Случайные целые числа в диапазоне от 0 до 10
random_int_array = np.random.randint(0, 10, size=5)
print(random_int_array)


[0.66106798 0.624995   0.30277407 0.17948929 0.87401848]
[3 5 4 2 5]


5. Линейная алгебра

In [5]:
# Умножение матриц
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)
print(matrix_product)

# Определитель матрицы
det_matrix1 = np.linalg.det(matrix1)
print(det_matrix1)  # -2.0000000000000004


[[19 22]
 [43 50]]
-2.0000000000000004
